packages:
  - .

ignoredBuiltDependencies:
  - better-sqlite3
  - extract-file-icon
  - node-window-manager

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - dprint
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - uiohook-napi
  - unrs-resolver
